version: '3.7'

networks:
  dim:
services:
  dimension:
    build:
      dockerfile: d_API.dockerfile
    environment:
      - LOG_LEVEL=TRACE
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - dim
  web-app:
    build:
      dockerfile: d_webapp.dockerfile
    environment:
      - LOG_LEVEL=TRACE
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - dim