version: '3.7'

networks:
  dim:
services:
  dimension:
    build:
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=TRACE
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - dim